name: 'action-mirror-commit-status'
description: 'Mirror a commit status from one check to another'
author: 'Iain Lane <iain@grafana.com>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    default: ${{ github.token }}
    required: false

  from-status:
    description: 'The name of the status to mirror from'
    required: true

  to-status:
    description: 'The name of the status to mirror to'
    required: true

runs:
  using: node20
  main: dist/index.js
