name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
